### ISSUE TITLE
About GPU RAM Requirement 

### ISSUE THREAD

**Issue by zzhou612** [HKUST-KnowComp/R-Net#1]
Sorry for disturbing you, but may I ask about the minimum GPU RAM required  for this model? I will be very grateful if you are willing to share the version of GPU you have used and the time it took to get the result.

**Comment by wzhouad** [comment]
This model requires 8.4 GB RAM. It takes about 52 min to train 1000 steps on Nvidia Titan X (Pascal).

**Comment by zzhou612** [comment]
Thank you very much for your swift reply!
