### ISSUE TITLE
Native GRU using Forward GRU instead of Backward GRU.

### ISSUE THREAD

**Issue by gangeshwark** [HKUST-KnowComp/R-Net#13]
In your func.py file, I believe line 95-96 should be using `gru_bw` instead of `gru_fw`.

Currently,
`out_bw, _ = tf.nn.dynamic_rnn(gru_fw, inputs_bw, seq_len, initial_state=init_bw, dtype=tf.float32)`
But should be,
`out_bw, _ = tf.nn.dynamic_rnn(gru_bw, inputs_bw, seq_len, initial_state=init_bw, dtype=tf.float32)`

Isn't it?

**Comment by wzhouad** [comment]
Thanks for your message. It's a bug and I've fixed it in the latest commit.

**Comment by gangeshwark** [comment]
Thanks for the quick update!
