### ISSUE TITLE
why only use the last answer ?

### ISSUE THREAD

**Issue by robbine** [HKUST-KnowComp/R-Net#15]
what if a question has multiple proper answers?
start, end = example["y1s"][-1], example["y2s"][-1]
y1[start], y2[end] = 1.0, 1.0

**Comment by wzhouad** [comment]
In training only one answer is used. You can also choose the answer randomly.

**Comment by robbine** [comment]
what if I create multiple examples each corresponding to an single answer.
Do you think it may improve the final f1/em score?

**Comment by wzhouad** [comment]
No.

**Comment by robbine** [comment]
good
