### ISSUE TITLE
Inaccurate prediction after reloading Model

### ISSUE THREAD

**Issue by shawei3000** [HKUST-KnowComp/R-Net#18]
This might be related to the known bug #13254 as well:
      I can train the model with "CUDNN" option as either 'true' (much faster) or 'false', both completed successfully and test accuracy were expected.
      But when I reload the model from the saved state, in both cases, models are providing wrong answers (though no python errors)..

Questions:
     1. would this bug impact non-CUDNN model option as well?
     2. if yes, is there any work-around?

**Comment by wzhouad** [comment]
check #5

**Comment by shawei3000** [comment]
Thanks!
