### ISSUE TITLE
Seems cudnn gru hidden size 100 is much faster ?

### ISSUE THREAD

**Issue by chenghuige** [HKUST-KnowComp/R-Net#19]
Thanks a lot for sharing this wonderful code, great help.
One thing interesting is when I set hidden size to 100 instead of 75, ie final output dim is 100 * 2 * 3 = 600 while by default is 75 * 2 * 3 = 450.
hidden size 100 batches/s:[4.39] insts/s:[281.20]
hidden size 75 will be batches/s:[3.35] insts/s:[214.44]
So confusing, why bigger hidden size faster ?

**Comment by wzhouad** [comment]
I know that the GPU performance is higher when the tensor size is a multiple of 4, but don't expect so much difference. I guess setting out dim to 76 has similar effect.

**Comment by chenghuige** [comment]
@wzhouad  Well, you are right,  just tried 76 has similar effect, thanks, closing this issue.
