### ISSUE TITLE
bucket not correct ?

### ISSUE THREAD

**Issue by chenghuige** [HKUST-KnowComp/R-Net#21]
in key_func t = tf.clip_by_value(buckets, 0, c_len) return tf.argmax(t)
but https://www.tensorflow.org/api_docs/python/tf/argmax say 
"Note that in case of ties the identity of the return value is not guaranteed."

if buckets is  [40,100]  input legnth is 30 then [30, 30] whith tf.argmax might return 0 or 1

So might change to do bucket like 
https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/utils/data_reader.py

**Comment by wzhouad** [comment]
How about changing bucket to [0, 40, 100]
