### ISSUE TITLE
CudnnRNNParamsSize Error

### ISSUE THREAD

**Issue by mickyyu96** [HKUST-KnowComp/R-Net#24]
Hello,
When i use CPU, it works normally. But when i use GPU, i got this error:

InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'CudnnRNNParamsSize' with these attrs.  Registered devices: [CPU], Registered kernels:
  device='GPU'; T in [DT_DOUBLE]; S in [DT_INT32]
  device='GPU'; T in [DT_FLOAT]; S in [DT_INT32]

Can someone help me solve this problem ?
Thanks.

**Comment by JianboTang** [comment]
I encounter the same problem.

**Comment by JianboTang** [comment]
I solve it.
I uninstall the tensorflow, and install tensorflow-gpu. it works.
therefore, the tensorflow==1.4.0 in requirements.txt should be modified to tensorflow-gpu==1.4.0

**Comment by JianboTang** [comment]
I solve it.
I uninstall the tensorflow, and install tensorflow-gpu. it works.
therefore, the tensorflow==1.4.0 in requirements.txt should be modified to tensorflow-gpu==1.4.0

**Comment by wzhouad** [comment]
Thanks for your solution. I'll update it in Readme.

**Comment by CuteCha** [comment]
@mickyyu96 when I use CPU, I got the same error. could you show your environment dependency or your python packages? Thanks

**Comment by mickyyu96** [comment]
Must it be version 1.4.0 ?
or can i use version 1.4.1 ?
