### ISSUE TITLE
Inference Module

### ISSUE THREAD

**Issue by tanmayb123** [HKUST-KnowComp/R-Net#27]
I'd like to use this project's code in a new version of my open source application, "askTanmay". Can you please create a module that simply takes a question & a paragraph, and returns the output from the neural net? It'd be much appreciated. Thanks!

**Comment by wzhouad** [comment]
The input pipeline is tfrecord, it may need to change a lot to allow interactive qa. I'll try.

**Comment by tanmayb123** [comment]
Thanks!

**Comment by wzhouad** [comment]
See if Inference.py is usable.

**Comment by burglarhobbit** [comment]
I'm getting this error on inference.py:

```
InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to
match. lhs shape= [1,1,75] rhs shape= [1,64,75]
```
the checkpoint requires 64 inputs while our inference feeds only 1 input.

**Comment by LouiseZJones** [comment]
Same error with @burglarhobbit.
