### ISSUE TITLE
training error

### ISSUE THREAD

**Issue by mickyyu96** [HKUST-KnowComp/R-Net#29]
As i told before in other issue, 
When i use CPU, it works normally. But when i use GPU, i got this error:

InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'CudnnRNNParamsSize' with these attrs. Registered devices: [CPU], Registered kernels:
device='GPU'; T in [DT_DOUBLE]; S in [DT_INT32]
device='GPU'; T in [DT_FLOAT]; S in [DT_INT32]

JianBoTang solve it with: 
I uninstall the tensorflow, and install tensorflow-gpu. it works.
therefore, the tensorflow==1.4.0 in requirements.txt should be modified to tensorflow-gpu==1.4.0

But if i uninstall my tensorflow 1.4.0 (tensorflow-gpu 1.4.0 still remain), i got this error:
ImportError: No module named 'tensorflow.python.ops.rnn_cell'

If i have both tensorflow and tensorflow-gpu: i got 'CudnnRNNParamsSize' error.

**Comment by wzhouad** [comment]
Please test the new version.

**Comment by fooSynaptic** [comment]
@wzhouad I only got RTX2080 which tf.1.4 cannot work for me, Can i have other solution to use GPU?
