### ISSUE TITLE
About Test & Evaluation (Unanswered Question Issue)

### ISSUE THREAD

**Issue by zzhou612** [HKUST-KnowComp/R-Net#3]
I have trained your model using GeForce GTX 1080 with reduced batch_size=55. After 60000 steps, I used `python config.py --mode test ` and got the following result:
`Exact Match: 69.69964664310955, F1: 78.46608330209344
`
Then I tried to remap the answer_dict so that the id in the answer_dict can stay consistent with dev-v1.1.json. I stored the remapped answer_dict to the json file, then used the official evaluation script to test the result.
the command I used:
`python evaluate-v1.1.py dev-v1.1.json predictions-remapped.json
`
the result I got:
`Exact Match: 67.18070009460737, F1: 75.63031756686154
`
I noticed that there were many unanswered questions. The output in the console looked like this:
```
...
Unanswered question 5733fe73d058e614000b6740 will receive score 0.
Unanswered question 57373d0cc3c5551400e51e85 will receive score 0.
Unanswered question 57377ec7c3c5551400e51f07 will receive score 0.
Unanswered question 57377ec7c3c5551400e51f09 will receive score 0.
Unanswered question 5737a0acc3c5551400e51f4b will receive score 0.
...
```

I have also checked the answer_dict (without remapping the id), the ids(=tot, tot+=1) should be series of continuous integers, however it seems that some of the numbers are missing.

Is this a desired behavior? Or does it have something to do with the preprocessing/testing procedure?

Thank you very much, looking forward to your reply.

**Comment by wzhouad** [comment]
In preprocessing, the questions are firstly assigned an id then filtered by context length, so if you map all question id to uuid, many questions will be missing.

**Comment by zzhou612** [comment]
Thanks a lot for your swift reply.
I have checked the maximum length of context/question tokens in the dev set:
```
max_len(context_tokens)=706
max_len(ques_tokens)=34
```
Then I increased `para_limit` and `ques_limit` to 5000 and 500 respectively to ensure that the question and answer pair in dev set will not be filtered by `filter_func`. Then I preprocessed the data again, and ran test to get the answer.
However, the Unanswered Question Issue remains (though the total number of the unanswered question reduced) and the performance increased to `Exact_match: 67.92809839167455, F1: 76.59515371470633`
Does it mean that I need to train my model again using the new filter constraint?

**Comment by wzhouad** [comment]
I also test the model with the official script and the F1 is only 0.1% lower than log. There may be some errors in your implementation. The number of unanswered questions should be less than the batch size (10 in my test).
The code now supports testing with the official script, and I'll release it today.

**Comment by zzhou612** [comment]
After lowing down the batch_size for testing, the problem was solved, thank you very much!
