### ISSUE TITLE
What is the reason switching to TF1.5.0?

### ISSUE THREAD

**Issue by qinyuhu** [HKUST-KnowComp/R-Net#30]
I was trying to make the code running for days and just noticed the TF version increased to 1.5.0.
I am currently using TF1.4.0 and wondering if this version update a must or not, is there any possibility I can modify the code and make it fit TF1.4.0.

One more reason asking this is because I was using a version before March 4th now and running using GPU with 24G RAM.But I encountered OOM issue that should not appear and have no idea why.

```
ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[18496,100]
	 [[Node: emb/char/bidirectional_rnn/fw/fw/while/fw/gru_cell/mul_1 = Mul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](emb/char/bidirectional_rnn/fw/fw/while/fw/gru_cell/split:1, emb/char/bidirectional_rnn/fw/fw/while/Switch_2:1)]]
	 [[Node: match/dot_attention/attention/Tile/multiples/_155 = _HostRecv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_2927_match/dot_attention/attention/Tile/multiples", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
```

**Comment by wzhouad** [comment]
1. In tf 1.4 there are bugs in cudnn rnn implementation, which are fixed in tf 1.5.
2. Preprocessing changed to support interactive QA.
3. 2 bugs fixed.

If you want to downgrade to tf 1.4, use model.py and func.py in last version and change line 25, 26 in func.py to
```python
init_fw = tf.tile(tf.Variable(tf.zeros([1, 1, num_units])), [1, batch_size, 1])
init_bw = tf.tile(tf.Variable(tf.zeros([1, 1, num_units])), [1, batch_size, 1])
```

The GPU memory needed is only 8.5gb. Check if the GPU is occupied by others or if there's problem in environment configuration.

**Comment by qinyuhu** [comment]
So just keep all the rest files up to March 15th's updates?

**Comment by wzhouad** [comment]
yes.
