### ISSUE TITLE
absl.flags._exceptions.IllegalFlagValueError

### ISSUE THREAD

**Issue by chenliangtao** [HKUST-KnowComp/R-Net#31]
I got this exception absl.flags._exceptions.IllegalFlagValueError: flag --bucket_range=[40, 401, 40]: Expect argument to be a string or int, found <class 'list'> at flags.DEFINE_integer("bucket_range", [40, 401, 40], "the range of bucket").
Sorry to say that I'm a beginner. Who can tell me why?

**Comment by wzhouad** [comment]
It has been fixed in the latest version

**Comment by chenliangtao** [comment]
@wzhouad Thank you. It worked after I updated to the latest version. But can I run this model on CPU-only machine?

**Comment by wzhouad** [comment]
Change use_cudnn in config.py to False.
