### ISSUE TITLE
softmax_mask

### ISSUE THREAD

**Issue by harryxu-yscz** [HKUST-KnowComp/R-Net#34]
This repo is written very nicely, thanks for sharing!

My question is not related with this system, just more about understanding RNet. I don't get why you use `softmax_mask()` before `softmax` operations. Could you explain more? Thanks again!

**Comment by wzhouad** [comment]
All sentences are padded to the same length. softmax_mask is used to filter out invalid positions.

**Comment by harryxu-yscz** [comment]
Thanks for the reply! Why not mask the inputs and outputs sequences of the RNN? Will this approach produce the same effect as yours?

**Comment by wzhouad** [comment]
Isn't masking outputs equivalent to masking softmax? Masking inputs is not necessary, tf handles it by input length.

**Comment by harryxu-yscz** [comment]
What about in the case of using `cudnn`? As there is no argument for it to specify input length.

**Comment by wzhouad** [comment]
Assume the length is 2, the output is [1, 1, 0], then after softmax is [0.42, 0.42, 0.16], wrong!
Masking it to [1, 1, -1e30] before softmax, then result is [1/2, 1/2, 0]
That's softmax_mask used for.

**Comment by harryxu-yscz** [comment]
Thanks this makes sense.
