### ISSUE TITLE
examples in func(build_features)

### ISSUE THREAD

**Issue by shiningliang** [HKUST-KnowComp/R-Net#37]
Thank you and great work!
I noticed the code in func _build_features_ in prepro.py that
`start, end = example["y1s"][-1], example["y2s"][-1]`
`y1[start], y2[end] = 1.0, 1.0`
Does it mean although you store the all the answer_spans for an question in y1s and y2s in func _process_file_ you only use the last answer_span for train when building features?

**Comment by wzhouad** [comment]
Yes.

**Comment by shiningliang** [comment]
OK. Thank you. And will this selection method of answer_span affect the result? After all the answers are differ from each other.

**Comment by wzhouad** [comment]
In bi-att-flow they randomly select the answer, while in match-lstm only the last answer is used. I don't think it has a big effect on the performance.

**Comment by shiningliang** [comment]
OK. Thank you very much!
