### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by anandpawara** [HKUST-KnowComp/R-Net#39]
FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "config.py", line 86, in <module>
    flags.DEFINE_list("bucket_range", [40, 361, 40], "range of bucket")
AttributeError: module 'tensorflow.python.platform.flags' has no attribute 'DEFINE_list'

**Comment by burglarhobbit** [comment]
`flags.DEFINE_list` is not supported <= tensorflow 1.4. You need to use tensorflow 1.5.

**Comment by utkarshpandey12** [comment]
You can change list into integer if you want to use it with tensor flow version less than 1.5.
