### ISSUE TITLE
I am trying to fine tune. But dimensionality mismatched of the tensors. Kindly give some solution.

### ISSUE THREAD

**Issue by brojokm** [HKUST-KnowComp/R-Net#40]

**Comment by burglarhobbit** [comment]
What kind of dimensionality mismatch?

For fine tuning, it is possible in this model. You have to restore the checkpoint after generating tf record dataset. Look into the [config file L73](https://github.com/HKUST-KnowComp/R-Net/blob/master/config.py#L73) to understand what kind of dimensions you need to keep for your dataset.

**Comment by brojokm** [comment]
word dictionary and char dictionary size is different. so their embedding dimension mismatched..

**Comment by wzhouad** [comment]
It's an interesting problem. Maybe the preprocessing is too awkward. You can try to modify that part and put correct word/char index. Dimensionality mismatch isn't a problem. You can exclude word/char embedding from model restoring.

**Comment by brojokm** [comment]
Hi! I'm new to tensorflow, and while I saw an option to selectively save a session, I don't exactly see how can I selectively restore, Another issue is that it seems that character embeddings are trainable. So what to do in this case? It'll be really helpful if you could elaborate on what I need to do.
Thanks in advance :)

**Comment by wzhouad** [comment]
In tf.train.Sever.__init__, the param var_list specifies the variables to save and restore. For char embedding, you can use a new one.
