### ISSUE TITLE
Error when using the pre-trained model in CPU

### ISSUE THREAD

**Issue by PhungVanDuy** [HKUST-KnowComp/R-Net#41]
I tried using R-Net with the pre-trained model (CPU version) at [Release version](https://github.com/HKUST-KnowComp/R-Net/releases).

But I got an error following:
![image](https://user-images.githubusercontent.com/28798474/39751154-7bb1938a-52e1-11e8-80c7-18950ffaa681.png)
My system: 
- Python: 3.5
- Tensorflow: 1.7.0

**Comment by wzhouad** [comment]
Set use_cudnn in config.py to False

**Comment by christinegrassi** [comment]
The checkpoint requires the use_cudnn flag to be set to true. It looks like this pretrained model cannot be used without GPU.
