### ISSUE TITLE
Which call method is adopted in calss cudnn_gru? '__call__' or 'call'?

### ISSUE THREAD

**Issue by luckmoon** [HKUST-KnowComp/R-Net#43]
In API document of tensorflow, there are two ``calls'' methods in tf.contrib.cudnn_rnn.CudnnGRU, which is '\__call\__' and 'call'. And when I see such codes:
`gru_fw = tf.contrib.cudnn_rnn.CudnnGRU(1, num_units)` 

`gru_fw(outputs[-1] * mask_fw, initial_state=(init_fw, ))`

I infer that you adopt the second call method as below
`call(
    inputs,
    initial_state=None,
    training=True
)`
Is that right? And why not write as 
`gru_fw.call((outputs[-1] * mask_fw, initial_state=(init_fw, )))`?

**Comment by wzhouad** [comment]
cudnn_gru inherits tf.python.layers.Layer, which will call ``call`` explicitely in ``__call__``.

**Comment by luckmoon** [comment]
gotcha, thank you.
