### ISSUE TITLE
Wrong attention at Question-Passage Matching Layer

### ISSUE THREAD

**Issue by cjerry1243** [HKUST-KnowComp/R-Net#45]
In the original paper, 
ct = att(uQ, [uPt, **vPt−1**])
the Q-P attention takes into account the last state's output vPt−1
while the implementation does not.

The Q-P attention and P-P self attention are somewhat different in the paper. The latter does not take into account the last output state of RNN.

**Comment by burglarhobbit** [comment]
True, this implementation does not use the standard attention (Bahdanau or
Luong) and rather uses the dot_attention. They have mentioned the paper
reference in their README: "Attention is all you need"
