### ISSUE TITLE
Why cudnn gru include 'multi_rnn_cell/cell_0/cudnn_compatible_gru_cell' ?

### ISSUE THREAD

**Issue by chenghuige** [HKUST-KnowComp/R-Net#47]
I find vars in the model generated 
encoding/bw_0/cudnn_gru/opaque_kernel (DT_FLOAT) [86184]
encoding/bw_0/cudnn_gru/rnn/multi_rnn_cell/cell_0/cudnn_compatible_gru_cell/candidate/hidden_projection/bias (DT_FLOAT) [76]
encoding/bw_0/cudnn_gru/rnn/multi_rnn_cell/cell_0/cudnn_compatible_gru_cell/candidate/hidden_projection/kernel (DT_FLOAT) [76,76]
encoding/bw_0/cudnn_gru/rnn/multi_rnn_cell/cell_0/cudnn_compatible_gru_cell/candidate/input_projection/bias (DT_FLOAT) [76]
encoding/bw_0/cudnn_gru/rnn/multi_rnn_cell/cell_0/cudnn_compatible_gru_cell/candidate/input_projection/kernel (DT_FLOAT) [300,76]
encoding/bw_0/cudnn_gru/rnn/multi_rnn_cell/cell_0/cudnn_compatible_gru_cell/gates/bias (DT_FLOAT) [152]
encoding/bw_0/cudnn_gru/rnn/multi_rnn_cell/cell_0/cudnn_compatible_gru_cell/gates/kernel (DT_FLOAT) [376,152]

Why there is multi_rnn_cell/cell_0/cudnn_compatible_gru_cell ?   
For when I only use your cudnn_gru code as encoder in other applications, and check the model saved I find only   
rnet/main/encoding/bw_0/cudnn_gru/opaque_kernel (DT_FLOAT) [86184]
no multi_rnn_cell.

**Comment by wzhouad** [comment]
I changed the implementation of rnn in v2.1. Are you comparing the same versions?
For detailed implementation of cudnn_gru, you can check the source code of tensorflow https://github.com/tensorflow/tensorflow/blob/r1.8/tensorflow/contrib/cudnn_rnn/python/layers/cudnn_rnn.py

**Comment by chenghuige** [comment]
@wzhouad  Thanks! Seems  opaque_kernel contains all info, so they perform the same. I removed init state which cause performance of f1 down lot, closing this issue.
