### ISSUE TITLE
Reprocessing Data Causing Error

### ISSUE THREAD

**Issue by zzhou612** [HKUST-KnowComp/R-Net#5]
The version 2 of your R-Net implementation worked perfectly. Following the `preprocess->train->test ` procedure I got the expected result. However, It seemed that if I preprocessed the data again, then the saved model failed to work correctly as it should be during the test procedure.

I have checked the generated files in the data folder, it seemed that `test_eval.json` and `word_emb.json`  changed each time after I had executed the preprocess command. Since the `eval_examples` were not shuffled and the `glove.840B.300d.txt` remained unchanged, this should not happened. This unexpected behavior really confused me.

**Comment by xiongyifan** [comment]
Are your word2idx_dict and char2idx_dict same as training time ?

**Comment by wzhouad** [comment]
In preprocess.py, line 106
```python
token2idx_dict = {token: idx for idx, token in enumerate(embedding_dict.keys(), 2)}
```
As in Python the dictionary keys don't preserve order, the index mapping changes each time, so the word embedding matrix changes each time. However, as word_emb is a Tensorflow variable, the original matrix will be restored. Same problem exists in char embedding. This will affect the performance. the eval file will also change, but will not affect the model.
If you need to regenerate the preprocess file, you can use the OrderedDict in Python.

**Comment by zzhou612** [comment]
Thank you very much~
