### ISSUE TITLE
Error running PreTrained Model , Mismatched Tensors

### ISSUE THREAD

**Issue by numericlee** [HKUST-KnowComp/R-Net#58]
Running the **pretrained model** (4/15/18 release) on  python 3.6     tensorflow 1.9   CPU produces the following error

        tensorflow.python.framework.errors_impl.InvalidArgumentError: 
        Assign requires shapes of both tensors to match. 
        lhs shape= [91596,300] rhs shape= [91589,300]`

### **ONE POSSIBLE CAUSE, SEEMINGLY RULED OUT**

When I unzipped the model and moved the data and log directories to **R-Net-master.**
There were two additional files (**word2idx.json and char2idx.json**) in the Home directory of the zip. 

In my first attempt I  copied those json files over to the R-Net-master/data directories, overwriting the previous versions

I wondered if those .json files were incompatible, causing the problem. So I renamed tnose .json files (by appending  _OLD to their names) then reran

        sh download.sh
        python config.py --mode prepro
        python config.py --mode test

and got the exact same error. Attached are the current contents of R-Net-master/data

![pretrained data](https://user-images.githubusercontent.com/32748976/43651848-7ef3dc96-9711-11e8-88a6-965f733749ce.png)

**Comment by wzhouad** [comment]
The shape of word_mat is [# number of tokens, 300]. The pretrained model is trained on SQuAD train.json and dev.json. So when you change the input file, loading will fail. To solve this problem, you can remove word_mat from TF saver.
