### ISSUE TITLE
character embedding is all zero

### ISSUE THREAD

**Issue by yanghanxy** [HKUST-KnowComp/R-Net#8]
Hi, 

Thanks for sharing this nice R-NET implementation!

I've got one question regarding the character embedding. 
I checked the `data/char_emb.json` file, and found out that all vectors are with value zero, which is quite weird. 
And then I checked the code for creating the character embedding, 
in `prepro.py`， line 100: 
```
        for token in filtered_elements:
            embedding_dict[token] = [0. for _ in range(vec_size)]
```

It seems that you encode each character to a vector of zeros with length `vec_size`.
I don't understand the meaning for this, beacuse this makes all characters identical in `tf.nn.embedding_lookup`. 
Could you explain why are you doing in this way? Thank you!

**Comment by wzhouad** [comment]
The character embedding is not used, the embedding is initialized in Tensorflow using Xavier.

**Comment by xiongyifan** [comment]
@yanghanxy Hi, thanks for adding the pre-trained glove character embedding vector.  Can you share the scores?

**Comment by yanghanxy** [comment]
Hi Yifan, 

sorry that I don't have the score by only adding the pre-trained character embedding vector, 
because I also modified other parts of the model architecture in my experiment.

Anyway, I will share with you if I could find out some tricks to improve the score.

**Comment by xiongyifan** [comment]
Wonderful, I also will share with you and Thanks for your response.
